name: Bolt CLI CI

on:
  push:
    branches:
      - unstable
      - main
    paths:
      - "bolt-cli/**"
  pull_request:
    paths:
      - "bolt-cli/**"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-tests:
    runs-on: self-hosted
    timeout-minutes: 10
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check
        run: |
          cd bolt-cli
          cargo check

      - name: Lint Code with Clippy
        run: |
          cd bolt-cli
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run bolt-cli tests
        run: |
          cd bolt-cli
          cargo nextest run --workspace --retries 3
